name: NBER

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  job_id:
    name: NBER
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        # python argument
        START: ${{ secrets.START }}
        END: ${{ secrets.END }}
        INTERVAL: ${{ secrets.INTERVAL }}

        # proxy
        PROXY_USER: ${{ secrets.PROXY_USER }}
        PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
        PROXY_HOST: ${{ secrets.PROXY_HOST }}
        PROXY_PORT: ${{ secrets.PROXY_PORT }}
        PROXY_SERVER: ${{ secrets.PROXY_SERVER }}

        # git
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: ${{ secrets.BRANCH }}
        EMAIL: ${{ secrets.EMAIL }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        # set up git
        git config --global user.email ${EMAIL}
        git config --global user.name ${USERNAME}
        git remote set-url origin https://${USERNAME}:${ACCESS_TOKEN}@github.com/${USERNAME}/nber.git
        
        # run script
        python src/nber.py --start ${START} --end ${END} --interval ${INTERVAL}
    - name: Commit changes
      run: |
        git add data/nber/*
        git commit --allow-empty -m "Update nber data"
        git pull --rebase origin ${BRANCH}
        git push -u origin ${BRANCH}
